# Generated by Django 4.1.5 on 2023-02-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cantidad',
            field=models.CharField(max_length=10),
        ),
    ]
