# Generated by Django 4.1.5 on 2023-02-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_reserva_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='Presentaciones',
            field=models.IntegerField(choices=[[0, '..........'], [1, '500g'], [2, '1kg'], [3, '2kg'], [4, '5kg'], [5, '10kg'], [6, '25kg'], [7, '50kg'], [8, 'Stick Packs']]),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='Productos',
            field=models.IntegerField(choices=[[0, '..........'], [1, 'Azucar Blanca'], [2, 'Azucar Morena'], [3, 'Azucar Ligero'], [4, 'Azucar Turbinado'], [5, 'Azucar Blanco Organico'], [6, 'Azucar De Coco Organico'], [7, 'Panela'], [8, 'Steviazucar Blanca'], [9, 'Steviazucar Morena'], [10, 'Stevia Panela']]),
        ),
    ]
